version: 2.1

executors:
  circleci-setup-executor:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    working_directory: ~/circleci-setup

jobs:
  testing:
    executor: circleci-setup-executor
    steps:
      - checkout
      - restore_cache:
          key: circleci-setup-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: circleci-setup-{{ checksum "pom.xml" }}
      - run: mvn verify
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: ~/circleci-setup
          # Must be relative path from root
          paths:
            - .

  mutation-testing:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/circleci-setup
      - restore_cache:
          key: circleci-setup-{{ checksum "pom.xml" }}
      - run: mvn org.pitest:pitest-maven:mutationCoverage

  static-analysis:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/circleci-setup
      - restore_cache:
          key: circleci-setup-{{ checksum "pom.xml" }}
      - run: mvn sonar:sonar -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.login=${SONAR_TOKEN} -Dsonar.host.url=${SONAR_HOST} -Dsonar.branch.name=${CIRCLE_BRANCH}

workflows:
  version: 2
  standart-workflow:
    jobs:
      - testing
      - mutation-testing:
          requires:
          - testing
      - static-analysis:
          requires:
            - mutation-testing
