version: 2.1

executors:
  circleci-setup-executor:
    docker:
      - image: circleci/openjdk:8u162-jdk


jobs:
  unit-test:
    executor: circleci-setup-executor
    steps:
      - checkout
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn test
      - persist_to_workspace:
          root: ~/
          paths:
            - .


  integration-test:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn verify -Dskip.surefire.tests=true
      - persist_to_workspace:
          root: ~/
          paths:
            - .


  mutation-test:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn org.pitest:pitest-maven:mutationCoverage
      - persist_to_workspace:
          root: ~/
          paths:
            - .


  static-analysis:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn sonar:sonar -Dsonar.organization=${SONAR_ORGANIZATION} -Dsonar.host.url=${SONAR_HOST} -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectKey=${PROJECT_KEY} -Dsonar.branch.name=${CIRCLE_BRANCH}


  spotbugs-analysis:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn spotbugs:check


  packaging:
    executor: circleci-setup-executor
    steps:
      - attach_workspace:
          at: ~/
      - restore_cache:
          key: ${CIRCLE_PROJECT_REPONAME}-{{ checksum "pom.xml" }}
      - run: mvn package -Dmaven.test.skip=true


workflows:
  version: 2
  standart-workflow:
    jobs:
      - unit-test
      - integration-test:
          requires:
            - unit-test
      - mutation-test:
          requires:
            - integration-test
      - static-analysis:
          requires:
            - mutation-test
      - spotbugs-analysis:
          requires:
            - mutation-test
      - packaging:
          requires:
            - static-analysis
            - spotbugs-analysis